# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: objects.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\robjects.proto\x12\x0btwitterdash\x1a\x1fgoogle/protobuf/timestamp.proto\"\x92\x01\n\x05Trend\x12)\n\ttrendType\x18\x01 \x01(\x0e\x32\x16.twitterdash.TrendType\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x03 \x01(\x05\x12\x11\n\tplacement\x18\x04 \x01(\x05\x12\x1a\n\rtweetVolume24\x18\x05 \x01(\x05H\x00\x88\x01\x01\x42\x10\n\x0e_tweetVolume24\"g\n\x12TrendProviderReply\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\"\n\x06trends\x18\x02 \x03(\x0b\x32\x12.twitterdash.Trend\"\xcf\x01\n\x05Tweet\x12\n\n\x02ID\x18\x01 \x01(\x03\x12\x17\n\x0f\x43onversation_ID\x18\x02 \x01(\x03\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04Text\x18\x04 \x01(\t\x12\x0e\n\x06UserID\x18\x05 \x01(\x03\x12\r\n\x05likes\x18\x06 \x01(\x05\x12\x0f\n\x07replies\x18\x07 \x01(\x05\x12\x10\n\x08retweets\x18\x08 \x01(\x05\x12\x10\n\x08Hashtags\x18\t \x03(\t\x12\x10\n\x08language\x18\n \x01(\t*#\n\tTrendType\x12\t\n\x05Topic\x10\x00\x12\x0b\n\x07Hashtag\x10\x01*,\n\x0bGranularity\x12\n\n\x06minute\x10\x00\x12\x08\n\x04hour\x10\x01\x12\x07\n\x03\x64\x61y\x10\x02\x62\x06proto3')

_TRENDTYPE = DESCRIPTOR.enum_types_by_name['TrendType']
TrendType = enum_type_wrapper.EnumTypeWrapper(_TRENDTYPE)
_GRANULARITY = DESCRIPTOR.enum_types_by_name['Granularity']
Granularity = enum_type_wrapper.EnumTypeWrapper(_GRANULARITY)
Topic = 0
Hashtag = 1
minute = 0
hour = 1
day = 2


_TREND = DESCRIPTOR.message_types_by_name['Trend']
_TRENDPROVIDERREPLY = DESCRIPTOR.message_types_by_name['TrendProviderReply']
_TWEET = DESCRIPTOR.message_types_by_name['Tweet']
Trend = _reflection.GeneratedProtocolMessageType('Trend', (_message.Message,), {
  'DESCRIPTOR' : _TREND,
  '__module__' : 'objects_pb2'
  # @@protoc_insertion_point(class_scope:twitterdash.Trend)
  })
_sym_db.RegisterMessage(Trend)

TrendProviderReply = _reflection.GeneratedProtocolMessageType('TrendProviderReply', (_message.Message,), {
  'DESCRIPTOR' : _TRENDPROVIDERREPLY,
  '__module__' : 'objects_pb2'
  # @@protoc_insertion_point(class_scope:twitterdash.TrendProviderReply)
  })
_sym_db.RegisterMessage(TrendProviderReply)

Tweet = _reflection.GeneratedProtocolMessageType('Tweet', (_message.Message,), {
  'DESCRIPTOR' : _TWEET,
  '__module__' : 'objects_pb2'
  # @@protoc_insertion_point(class_scope:twitterdash.Tweet)
  })
_sym_db.RegisterMessage(Tweet)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRENDTYPE._serialized_start=527
  _TRENDTYPE._serialized_end=562
  _GRANULARITY._serialized_start=564
  _GRANULARITY._serialized_end=608
  _TREND._serialized_start=64
  _TREND._serialized_end=210
  _TRENDPROVIDERREPLY._serialized_start=212
  _TRENDPROVIDERREPLY._serialized_end=315
  _TWEET._serialized_start=318
  _TWEET._serialized_end=525
# @@protoc_insertion_point(module_scope)
