# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TweetService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import objects_pb2 as objects__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12TweetService.proto\x12\x0btwitterdash\x1a\robjects.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa8\x01\n\x10GetTweetsRequest\x12\r\n\x05trend\x18\x01 \x01(\t\x12\x11\n\tlanguages\x18\x02 \x03(\t\x12)\n\x05since\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12)\n\x05until\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\x05limit\x18\x05 \x01(\x05H\x00\x88\x01\x01\x42\x08\n\x06_limit\"4\n\x0eGetTweetsReply\x12\"\n\x06tweets\x18\x01 \x03(\x0b\x32\x12.twitterdash.Tweet2Z\n\rTweetProvider\x12I\n\tGetTweets\x12\x1d.twitterdash.GetTweetsRequest\x1a\x1b.twitterdash.GetTweetsReply\"\x00\x62\x06proto3')



_GETTWEETSREQUEST = DESCRIPTOR.message_types_by_name['GetTweetsRequest']
_GETTWEETSREPLY = DESCRIPTOR.message_types_by_name['GetTweetsReply']
GetTweetsRequest = _reflection.GeneratedProtocolMessageType('GetTweetsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETTWEETSREQUEST,
  '__module__' : 'TweetService_pb2'
  # @@protoc_insertion_point(class_scope:twitterdash.GetTweetsRequest)
  })
_sym_db.RegisterMessage(GetTweetsRequest)

GetTweetsReply = _reflection.GeneratedProtocolMessageType('GetTweetsReply', (_message.Message,), {
  'DESCRIPTOR' : _GETTWEETSREPLY,
  '__module__' : 'TweetService_pb2'
  # @@protoc_insertion_point(class_scope:twitterdash.GetTweetsReply)
  })
_sym_db.RegisterMessage(GetTweetsReply)

_TWEETPROVIDER = DESCRIPTOR.services_by_name['TweetProvider']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETTWEETSREQUEST._serialized_start=84
  _GETTWEETSREQUEST._serialized_end=252
  _GETTWEETSREPLY._serialized_start=254
  _GETTWEETSREPLY._serialized_end=306
  _TWEETPROVIDER._serialized_start=308
  _TWEETPROVIDER._serialized_end=398
# @@protoc_insertion_point(module_scope)
