version: '3.8'
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongorootpassword

  # python:
  #   container_name: python
  #   build: ./<path>
  #   restart: unless-stopped

  # dotnet:
  #   container_name: dotnet
  #   build: ./<path>
  #   restart: unless-stopped

  # frontend:
  #   container_name: frontend
  #   build: .
  #   restart: unless-stopped
  #   ports:
  #     - "8080:80"