# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SentimentService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16SentimentService.proto\x12\x0btwitterdash\"5\n\x13GetSentimentRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\"&\n\x11GetSentimentReply\x12\x11\n\tsentiment\x18\x01 \x01(\x02\x32g\n\x11SentimentProvider\x12R\n\x0cGetSentiment\x12 .twitterdash.GetSentimentRequest\x1a\x1e.twitterdash.GetSentimentReply\"\x00\x62\x06proto3')



_GETSENTIMENTREQUEST = DESCRIPTOR.message_types_by_name['GetSentimentRequest']
_GETSENTIMENTREPLY = DESCRIPTOR.message_types_by_name['GetSentimentReply']
GetSentimentRequest = _reflection.GeneratedProtocolMessageType('GetSentimentRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSENTIMENTREQUEST,
  '__module__' : 'SentimentService_pb2'
  # @@protoc_insertion_point(class_scope:twitterdash.GetSentimentRequest)
  })
_sym_db.RegisterMessage(GetSentimentRequest)

GetSentimentReply = _reflection.GeneratedProtocolMessageType('GetSentimentReply', (_message.Message,), {
  'DESCRIPTOR' : _GETSENTIMENTREPLY,
  '__module__' : 'SentimentService_pb2'
  # @@protoc_insertion_point(class_scope:twitterdash.GetSentimentReply)
  })
_sym_db.RegisterMessage(GetSentimentReply)

_SENTIMENTPROVIDER = DESCRIPTOR.services_by_name['SentimentProvider']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETSENTIMENTREQUEST._serialized_start=39
  _GETSENTIMENTREQUEST._serialized_end=92
  _GETSENTIMENTREPLY._serialized_start=94
  _GETSENTIMENTREPLY._serialized_end=132
  _SENTIMENTPROVIDER._serialized_start=134
  _SENTIMENTPROVIDER._serialized_end=237
# @@protoc_insertion_point(module_scope)
