# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TrendService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import objects_pb2 as objects__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12TrendService.proto\x12\x0btwitterdash\x1a\robjects.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf4\x01\n\x1bGetRecentTweetCountsRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x33\n\nstart_date\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00\x88\x01\x01\x12\x31\n\x08\x65nd_date\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x01\x88\x01\x01\x12\x32\n\x0bgranularity\x18\x04 \x01(\x0e\x32\x18.twitterdash.GranularityH\x02\x88\x01\x01\x42\r\n\x0b_start_dateB\x0b\n\t_end_dateB\x0e\n\x0c_granularity\"I\n\nTweetCount\x12,\n\x08\x64\x61tetime\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"I\n\x19GetRecentTweetCountsReply\x12,\n\x0btweetCounts\x18\x01 \x03(\x0b\x32\x17.twitterdash.TweetCount2[\n\rTrendProvider\x12J\n\x0bOnNewTrends\x12\x16.google.protobuf.Empty\x1a\x1f.twitterdash.TrendProviderReply\"\x00\x30\x01\x32\x81\x01\n\x13TweetCountsProvider\x12j\n\x14GetRecentTweetCounts\x12(.twitterdash.GetRecentTweetCountsRequest\x1a&.twitterdash.GetRecentTweetCountsReply\"\x00\x62\x06proto3')



_GETRECENTTWEETCOUNTSREQUEST = DESCRIPTOR.message_types_by_name['GetRecentTweetCountsRequest']
_TWEETCOUNT = DESCRIPTOR.message_types_by_name['TweetCount']
_GETRECENTTWEETCOUNTSREPLY = DESCRIPTOR.message_types_by_name['GetRecentTweetCountsReply']
GetRecentTweetCountsRequest = _reflection.GeneratedProtocolMessageType('GetRecentTweetCountsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETRECENTTWEETCOUNTSREQUEST,
  '__module__' : 'TrendService_pb2'
  # @@protoc_insertion_point(class_scope:twitterdash.GetRecentTweetCountsRequest)
  })
_sym_db.RegisterMessage(GetRecentTweetCountsRequest)

TweetCount = _reflection.GeneratedProtocolMessageType('TweetCount', (_message.Message,), {
  'DESCRIPTOR' : _TWEETCOUNT,
  '__module__' : 'TrendService_pb2'
  # @@protoc_insertion_point(class_scope:twitterdash.TweetCount)
  })
_sym_db.RegisterMessage(TweetCount)

GetRecentTweetCountsReply = _reflection.GeneratedProtocolMessageType('GetRecentTweetCountsReply', (_message.Message,), {
  'DESCRIPTOR' : _GETRECENTTWEETCOUNTSREPLY,
  '__module__' : 'TrendService_pb2'
  # @@protoc_insertion_point(class_scope:twitterdash.GetRecentTweetCountsReply)
  })
_sym_db.RegisterMessage(GetRecentTweetCountsReply)

_TRENDPROVIDER = DESCRIPTOR.services_by_name['TrendProvider']
_TWEETCOUNTSPROVIDER = DESCRIPTOR.services_by_name['TweetCountsProvider']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETRECENTTWEETCOUNTSREQUEST._serialized_start=113
  _GETRECENTTWEETCOUNTSREQUEST._serialized_end=357
  _TWEETCOUNT._serialized_start=359
  _TWEETCOUNT._serialized_end=432
  _GETRECENTTWEETCOUNTSREPLY._serialized_start=434
  _GETRECENTTWEETCOUNTSREPLY._serialized_end=507
  _TRENDPROVIDER._serialized_start=509
  _TRENDPROVIDER._serialized_end=600
  _TWEETCOUNTSPROVIDER._serialized_start=603
  _TWEETCOUNTSPROVIDER._serialized_end=732
# @@protoc_insertion_point(module_scope)
