import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Trends from '../components/Trends'
import TweetCountsChart from '../components/tweet_count_chart'
import React, { useEffect, useState, Fragment } from "react";

export default class Home extends React.Component {
    constructor() {
        super();
        this.onSelectChange = this.onSelectChange.bind(this);
        this.state = {
            selected_hashtag: null
        }
    }

    onSelectChange(e) {
        this.setState({
            selected_hashtag: e.target.value
        });
        console.log("state is gonna change")
    }

    render() {
        console.log("render")
        console.log(this.state.selected_hashtag)
        return (
            <div className={styles.container}>
                <Head>
                    <title>Twitter Dash</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className={styles.main}>

                    <h1 className={styles.title}>
                        Twitter Dash
                    </h1>
                    <select onChange={this.onSelectChange}>
                        <option disabled selected value> select hashtag </option>
                        <option value="BTS_Proof">#BTS_Proof</option>
                        <option value="YetToCome">#YetToCome</option>
                    </select>
                    <div id="tweet_counts_chart">
                        <TweetCountsChart hashtag={this.state.selected_hashtag}></TweetCountsChart>
                    </div>
                    <Trends></Trends>

                </main>
            </div>
        )
    }

}
